### ISSUE TITLE
[Research] Identify existing tests in CNTI Test Catalog that are in alignment with Anuket Test Case Traceability to RA2 Requirements

### ISSUE THREAD

**Issue by lixuna** [cnti-testcatalog/testcatalog#3]
# Research: 
- Identify existing tests in CNTI Test Catalog that are in alignment with [Anuket Test Case Traceability to RA2 Requirements](https://cntt.readthedocs.io/projects/rc2/en/stable-nile/chapters/chapter04.html#traceability-matrix)

### Tasks: 

- ~~[ ] Review RA2 specifications for Anuket Workloads:
https://cntt.readthedocs.io/projects/ra2/en/stable-orinoco/chapters/chapter04.html#kubernetes-workloads~~
- [x] Review RC2 Test Cases and Requirements for Anuket Workloads:
https://cntt.readthedocs.io/projects/rc2/en/stable-orinoco/chapters/chapter04.html
- [x] Create a report that shows CNTI tests that are in alignment with Anuket requirements
- [x] Share report with CNTI Best Practices team 
- [x] Share report with CNTI Certification team 
- [x] Share report with Anuket team

**Comment by lixuna** [comment]
Please review the analysis started at https://docs.google.com/document/d/1iXYVw5jdOMrzds64qAOYuf-x5kGE2oVzpaOrQZ05Xtc/edit#heading=h.tmdrkdxp5hi4

**Comment by taylor** [comment]
I am updating this to focus on the RC2 test case requirements instead of all areas of Anuket -> [4.3.1. Test Case Traceability to RA2 Requirements](https://cntt.readthedocs.io/projects/rc2/en/stable-orinoco/chapters/chapter04.html#test-case-traceability-to-ra2-requirements) - _Anuket Reference Conformance for RA2 based Implementations (RC2)_

**Comment by taylor** [comment]
New release: stable-orinoco
- https://cntt.readthedocs.io/projects/rc2/en/stable-orinoco/chapters/chapter04.html

**Comment by taylor** [comment]
There are some tests missing in the RC2 test matrix that are available from the test suite. For example

>  RM/RA Ref: ra2.app.034
> Desc: Container image tags: All referred container images in the Pod manifests must be referred by a version tag pointing to a concrete version of the image. latest tag must not be used
> Provided by: N/A
> Priority: Must


![image](https://github.com/cnti-testcatalog/testcatalog/assets/26697/ef739302-c5b9-4639-b30e-5942bc7a23fd)
![image](https://github.com/cnti-testcatalog/testcatalog/assets/26697/35d8d154-6594-4549-83cf-551e635f3fc7)
![image](https://github.com/cnti-testcatalog/testcatalog/assets/26697/3e0c4316-b42e-4f4b-97e0-c5f219a115ee)

**Comment by taylor** [comment]
References:
- rc2 tests are called from this in Anuket https://gerrit.opnfv.org/gerrit/gitweb?p=functest-kubernetes.git;a=tree
- testing results https://gerrit.opnfv.org/gerrit/gitweb?p=functest-kubernetes.git;a=blob_plain;f=README.md;hb=HEAD
-  test config for k8s  https://gerrit.opnfv.org/gerrit/gitweb?p=functest-kubernetes.git;a=blob_plain;f=setup.cfg;hb=HEAD
- https://gerrit.opnfv.org/gerrit/gitweb?p=functest-kubernetes.git;a=tree

**Comment by taylor** [comment]
maybe 
![image](https://github.com/cnti-testcatalog/testcatalog/assets/26697/e233a0ff-e401-41d8-8ce8-ff97348f6a59)

**Comment by taylor** [comment]
Review in Ornico release and current test suite main branch.  The following tests have "N/A' or "TBD" in the column titled "Test name and Project" in the RC2 documentation.
 
- [x] ra2.app.024 - CNF resiliency (pod DNS error): CNF must not lose data, must continue to run and its readiness probe outcome must be Success even in case of pod DNS error occurs.
    - [x] missing in Anuket
    -  Anuket priority -> Must
    - [x] available in test catalog
       - [x] Documentation for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/docs/LIST_OF_TESTS.md#pod-dns-errors
       - [x] Code for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/spec/workload/resilience/pod_dns_error_spec.cr#L8
       - [x] Listed as cert test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/src/tasks/cert/cert_resilience.cr#L16
       - [x] Check for priority in certification: test is not an Essential test for v1.1-beta but maybe it should be for v2.0-beta since it is a MUST requirement for Anuket.  
- [x] ra2.app.028 - No access to container daemon sockets: The CNF must not have any of the container daemon sockets (e.g.: /var/run/docker.sock, /var/run/containerd.sock or /var/run/crio.sock) mounted.
    - [x] missing in Anuket
    -  Anuket priority -> Must
    - [x] available in test catalog
       - [x] Documentation for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/docs/LIST_OF_TESTS.md#container-socket-mounts
       - [x] Code for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/src/tasks/workload/security.cr#L138
       - [x] Listed as cert test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/src/tasks/cert/cert_security.cr#L22
       - [x] Check for priority in certification: test is already an Essential test for v1.1-beta.
- [x] ra2.app.034 - Container image tags: All referred container images in the Pod manifests must be referred by a version tag pointing to a concrete version of the image. latest tag must not be used 
    - [x] missing in Anuket
     -  Anuket priority -> Must
    - [x] available in test catalog
       - [x] Documentation for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/docs/LIST_OF_TESTS.md#latest-tag
       - [x] Code for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/src/tasks/workload/configuration.cr#L92
       - [x] Listed as cert test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/src/tasks/cert/cert_configuration.cr#L20
       - [x] Check for priority in certification: test is already an Essential test for v1.1-beta. 
- [x] ra2.app.038 - If the CNF supports scaling, increasing and decreasing its capacity must be implemented using horizontal scaling. If horizontal scaling is supported, automatic scaling must be possible using Kubernetes Horizontal Pod Autoscale [Horizontal Pod Autoscale (HPA)](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) feature.
    - [x] missing in Anuket
     -  Anuket priority -> Must
    - [x] available in test catalog
       - [x] Documentation for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/docs/LIST_OF_TESTS.md#increase-decrease-capacity
       - [ ] Code for test:  
         -  There is not an exact match, however there is a test that is similar and may be of interest to Anuket.
       - [x] Listed as cert test https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#increase-decrease-capacity
       - [x] Check for priority in certification.
         - Not an existing test currently, but this is a Must test for Anuket.

**Comment by taylor** [comment]
Review in Ornico release and current test suite main branch. The following tests have "_blank_" in the column titled "Test name and Project" in the RC2 documentation.

- ra2.app.047 - The Pods of the CNF should not use the host ports. Using the host ports ties the CNF to a specific node, thereby making the CNF less portable and scalable. 
    - [x] missing in Anuket
    -  Anuket priority -> Must
    - [x] available in test catalog
       - [x] Documentation for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/docs/LIST_OF_TESTS.md#hostport-not-used
       - [x] Code for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/spec/workload/configuration_spec.cr#L230
       - [x] Listed as cert test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/src/tasks/cert/cert_configuration.cr#L26
       - [x] Check for priority in certification: test is already an Essential test for v1.1-beta. 

 - ra2.app.048 - If SELinux is used in the Pods of the CNF, the options used to escalate privileges should not be allowed. The options spec.securityContext.seLinuxOptions.type, spec.containers[*].securityContext.seLinuxOptions.type, spec.initContainers[*].securityContext.seLinuxOptions, and spec.ephemeralContainers[*].securityContext.seLinuxOptions.type must either be unset altogether or set to one of the following allowed values container_t, container_init_t, or container_kvm_t.    
    - [x] missing in Anuket
    -  Anuket priority -> Must
    - [x] available in test catalog
       - [x] Documentation for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/docs/LIST_OF_TESTS.md#selinux-options
       - [x] Code for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/spec/workload/security_spec.cr#L389
       - [x] Listed as cert test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/src/tasks/cert/cert_resilience.cr#L16
       - [x] Check for priority in certification: test is already an Essential test for v1.1-beta

**Comment by lixuna** [comment]
List of Tests available in  https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md

The List of Essential Tests are:
[latest_tag](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#latest-tag)
[selinux_options](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#selinux-options)
[single_process_type](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#single-process-type-in-one-container)
[node_drain](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#node-drain)
[liveness](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#helm-chart-liveness)
[readiness](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#helm-chart-readiness)
[log_output](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#use-stdoutstderr-for-logs)
[container_sock_mounts](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#container-socket-mounts)
[privileged_containers](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#privileged-containers-kubescape)
[non_root_containers](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#non-root-containers)
[resource_policies](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#resource-policies)
[hostpath_mounts](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#hostpath-mounts)
[hostport_not_used](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#hostport-not-used)
[hardcoded_ip_addresses_in_k8s_runtime_configuration](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#hardcoded-ip-addresses-in-k8s-runtime-configuration)
[increase_decrease_capacity](https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md#increase-decrease-capacity)

**Comment by Smitholi67** [comment]
List of Essential Tests v1.1:  https://github.com/lfn-cnti/certification/blob/main/docs/CNFCertification-1.1-beta.md

**Comment by Smitholi67** [comment]
Review in Ornico release and current test suite main branch. The following tests have "Kubernetes" or links to other documentation in the column titled "Test name and Project" in the RC2 documentation.

- ra2.app.007 - Workloads must not use hostPath volumes, as Pods with identical configuration (such as those created from a PodTemplate) may behave differently on different nodes due to different files on the nodes.

    - [x] missing in Anuket
    -  Anuket priority -> Must
    - [x] available in test catalog
       - [x] Documentation for test https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/docs/LIST_OF_TESTS.md#volume-hostpath-not-found
       - [x] Code for test:  https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/spec/workload/state_spec.cr#L81
       - [x] Listed as cert test:  https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/src/tasks/cert/cert_state.cr#L10
       - [x] Check for priority in certification:   Test is not an Essential test for v1.1-beta but maybe it should be for v2.0-beta since it is a MUST requirement for Anuket.


- ra2.app.009 - Device Plugins. Workload descriptors must use the resources advertised by the device plugins to indicate their need for an FPGA, SR-IOV or other acceleration device.

    - [x] missing in Anuket
    -  Anuket priority -> Must
    - [ ] available in test catalog
       - [ ] Documentation for test: not found
       - [ ] Code for test:  not found
       - [ ] Listed as cert test: not found
       - [ ] Check for priority in certification:  not found

- ra2.app.010 - Node Feature Discovery (NFD). Workload descriptors must use the labels advertised by Node Feature Discovery to indicate which node software of hardware features they need.

    - [x] missing in Anuket
    -  Anuket priority -> Must
    - [ ] available in test catalog
       - [ ] Documentation for test:  not found 
       - [ ] Code for test:  not found
       - [ ] Listed as cert test:  not found
       - [ ] Check for priority in certification: not found 

- ra2.app.046 - The Pods of the CNF must direct their logs to sdout or stderr. This enables the treatment of the logs as event steams. 

    - [x] missing in Anuket
    -  Anuket priority -> Must
    - [x] available in test catalog
       - [x] Documentation for test: https://github.com/cnti-testcatalog/testsuite/blob/main/docs/LIST_OF_TESTS.md#use-stdoutstderr-for-logs
       - [x] Code for test: https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/spec/workload/observability_spec.cr#L13
       - [x] Listed as cert test: https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/src/tasks/cert/cert_observability.cr#L9
       - [x] Check for priority in certification:  test is already an Essential test for v1.1-beta.

**Comment by Smitholi67** [comment]
@taylor @lixuna - Please review the report that is to be shared with Anuket, the CNTI Best Practices Focus Area, and the CNTI Certification Focus Area.
